name: Build

on:
  push:
    branches:
      - master
    tags:
      - "v*"
    paths-ignore:
      - "*.md"
      - "**/.gitignore"
      - "assets/**/*"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "*.md"
      - "**/.gitignore"
      - "images/**/*"
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Commit Information
        id: commit
        run: |
          echo "commit_message=$(git log -1 --pretty=%s)" >> $env:GITHUB_OUTPUT
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
          cache: true
          cache-dependency-path: PCTRGen6/packages.lock.json
      - name: Build
        run: |
          dotnet publish PCTRGen6 -c Release -o Release
          Compress-Archive -Path "Release/*" -Destination "PCTRGen6.zip" -Force
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PCTRGen6
          path: Release/*
      - name: Create release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: PCTRGen6.zip
          name: "${{ github.ref_name }}"
          draft: true
          tag: "${{ github.ref_name }}"
      - name: Publish draft release
        if: github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: PCTRGen6.zip
          name: "${{ github.event.head_commit.message }}"
          prerelease: true
          tag: publish
